version: '3.8'
services:
  bootstrap:
    build:
      context: ..
      dockerfile: docker_config/Dockerfile
    ports:
      - "8081:8081"  # Bootstrap TCP listener
      - "8090:8090"  # Web server port
    command: ["cargo", "run", "--release", "8090", "8081"]
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8081"]
      interval: 10s
      timeout: 5s
      retries: 5

  node1:
    build:
      context: ..
      dockerfile: docker_config/Dockerfile
    depends_on:
      bootstrap:
        condition: service_healthy
    ports:
      - "8080:8080"
    command: ["cargo", "run", "--release", "8080", "8081"]

  node2:
    build:
      context: ..
      dockerfile: docker_config/Dockerfile
    depends_on:
      bootstrap:
        condition: service_healthy
    ports:
      - "8082:8082"
    command: ["cargo", "run", "--release", "8082", "8081"]
